"""CI matrix generator: output affected packages for CI systems."""

import json
from typing import Optional

from .detector import Package
from .impact import ImpactReport
from .graph import DependencyGraph


def generate_github_actions_matrix(
    report: ImpactReport,
    dep_graph: DependencyGraph,
    include_fields: Optional[list[str]] = None,
) -> dict:
    """Generate a GitHub Actions matrix JSON for affected packages.

    Output format:
    {
        "include": [
            {"package": "pkg-a", "path": "packages/pkg-a", "type": "npm"},
            ...
        ]
    }
    """
    include_fields = include_fields or ["package", "path", "type"]
    entries = []

    for name in sorted(report.all_affected):
        pkg = dep_graph.packages.get(name)
        if not pkg:
            continue
        entry = {}
        if "package" in include_fields:
            entry["package"] = pkg.name
        if "path" in include_fields:
            entry["path"] = pkg.path
        if "type" in include_fields:
            entry["type"] = pkg.pkg_type
        if "direct" in include_fields:
            entry["direct"] = name in report.directly_changed
        entries.append(entry)

    return {"include": entries}


def generate_plain_list(
    report: ImpactReport,
    dep_graph: DependencyGraph,
    format: str = "names",
) -> list[str]:
    """Generate a plain list of affected packages.

    Args:
        format: "names" (package names), "paths" (package paths), "json" (JSON per line)
    """
    result = []
    for name in sorted(report.all_affected):
        pkg = dep_graph.packages.get(name)
        if not pkg:
            continue
        if format == "paths":
            result.append(pkg.path)
        elif format == "json":
            result.append(json.dumps({
                "name": pkg.name,
                "path": pkg.path,
                "type": pkg.pkg_type,
                "direct": name in report.directly_changed,
            }))
        else:
            result.append(pkg.name)
    return result


def generate_build_order(
    report: ImpactReport,
    dep_graph: DependencyGraph,
) -> list[list[str]]:
    """Generate build order in layers (parallelizable within each layer).

    Returns list of layers, where each layer can be built in parallel.
    Layer 0 has no dependencies on other affected packages, etc.
    """
    affected = report.all_affected
    if not affected:
        return []

    # Build subgraph of affected packages
    sub = dep_graph.subgraph(affected)
    remaining = set(affected)
    layers: list[list[str]] = []

    while remaining:
        # Find packages with no unprocessed dependencies in the subgraph
        layer = []
        for name in sorted(remaining):
            deps_in_sub = sub.direct_dependencies(name)
            if not (deps_in_sub & remaining - {name}):
                layer.append(name)

        if not layer:
            # Cycle detected, just dump remaining
            layers.append(sorted(remaining))
            break

        layers.append(layer)
        remaining -= set(layer)

    return layers


def generate_gitlab_ci(
    report: ImpactReport,
    dep_graph: DependencyGraph,
) -> str:
    """Generate GitLab CI parallel job configuration."""
    lines = ["# Auto-generated by mono-radar", ""]

    build_order = generate_build_order(report, dep_graph)
    for stage_idx, layer in enumerate(build_order):
        stage_name = f"stage-{stage_idx}"
        for name in layer:
            pkg = dep_graph.packages.get(name)
            if not pkg:
                continue
            lines.append(f"build-{name}:")
            lines.append(f"  stage: {stage_name}")
            lines.append(f"  script:")
            if pkg.pkg_type in ("npm", "pnpm"):
                lines.append(f"    - cd {pkg.path} && npm ci && npm test")
            elif pkg.pkg_type == "cargo":
                lines.append(f"    - cd {pkg.path} && cargo test")
            elif pkg.pkg_type == "go":
                lines.append(f"    - cd {pkg.path} && go test ./...")
            elif pkg.pkg_type == "python":
                lines.append(f"    - cd {pkg.path} && pip install -e . && pytest")
            lines.append("")

    return "\n".join(lines)
